name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: clone rathle
        run: git clone https://github.com/rapiz1/rathole

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: aarch64-unknown-linux-musl
          toolchain: stable
          args: "--locked --release --manifest-path rathole/Cargo.toml"
          strip: true
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@master
        with:
          command: "build"
          target: x86_64-unknown-linux-musl
          toolchain: stable
          args: "--locked --release --manifest-path rathole/Cargo.toml"
          strip: true

      - name: Build and push Docker images
        id: docker_build_x86
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/dvdplaat/rathole:amd64
          build-args: |
            ARCH=x86_64-unknown-linux-musl
          secrets: |
            GITHUB_TOKEN

      - name: Build and push Docker images
        id: docker_build_arm
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/dvdplaat/rathole:arm64
          build-args: |
            ARCH=aarch64-unknown-linux-musl
          secrets: |
            GITHUB_TOKEN
